# Generated by Django 6.0.2 on 2026-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('negotiable', 'Negotiable'), ('request', 'On Request')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
