# Generated by Django 6.0.2 on 2026-03-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_category_alter_crop_name_alter_crop_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='users.category'),
        ),
    ]
