# Generated by Django 6.0.2 on 2026-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'crop')},
        ),
    ]
