# Generated by Django 6.0.2 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
